topic1:
  name: '/piksi_multi_base_station/navsatfix_rtk_fix'
  column_names:
    column_name1: 'lat'
    column_name2: 'lon'
    column_name3: 'sats'
  parameters:
    param1: 'latitude'
    param2: 'longitude'
    param3: 'n_sats'

topic2:
  name: '/odometry/filtered_map'
  column_names:
    column_name1: 'x'
    column_name2: 'y'
  parameters:
    param1: 'pose.pose.position.x'
    param2: 'pose.pose.position.y'

topic3:
  name: '/piksi_multi_base_station/pos_llh'
  column_names:
    column_name1: 'haccuracy'
    column_name2: 'vaccuracy'
    column_name3: 'height'
  parameters:
    param1: 'h_accuracy'
    param2: 'v_accuracy'
    param3: 'height'
